apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  namespace: {{ENV}}
  name: itunes-appstore-project
spec:
  revisionHistoryLimit: 2
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: itunes-appstore-project
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: itunes-appstore-project
        image: quay.io/onesky/itunes-appstore-project:{{IMG_VERSION}}
        ports:
        - containerPort: 50051
          name: rpc
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
          - name: JAVA_TOOL_OPTIONS 
            value: "-Xms128m -Xmx500m"
          - name: ITUNES_APPSTORE_PROJECT_SERVICE_ADDRESS
            value: 127.0.0.1
          - name: ORDERING_SERVICE_ADDRESS
            value: "ordering.{{ENV}}.svc.cluster.local"
          - name: ITUNES_TRANSLATION_ADDRESS
            value: "itunes-translation.{{ENV}}.svc.cluster.local"
          - name: TRANSLATOR_ALLOCATION_ADDRESS
            value: "legacy-ta.{{ENV}}.svc.cluster.local"
          - name: ITUNES_APPSTORE_ORDER_SERVICE_ADDRESS
            #value: "itunes-appstore-project.{{ENV}}.svc.cluster.local"
            value: 127.0.0.1
          - name: APPSTORE_INTEGRATION_SERVICE_ADDRESS
            value: "appstore-integration.{{ENV}}.svc.cluster.local"
          - name: CONTACT_SERVICE_ADDRESS
            value: "client.{{ENV}}.svc.cluster.local"
          - name: ITUNES_CONNECT_SERVICE_ADDRESS
            value: 127.0.0.1
          - name: PGSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: itunes-appstore-project
                key: pgsql.host
          - name: PGSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: itunes-appstore-project
                key: pgsql.database
          - name: PGSQL_PORT
            valueFrom:
              configMapKeyRef:
                name: itunes-appstore-project
                key: pgsql.port
          - name: PGSQL_USERNAME
            valueFrom:
              configMapKeyRef:
                name: itunes-appstore-project
                key: pgsql.username
          - name: PGSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: itunes-appstore-project
                key: pgsql.password
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: rabbitmq
                key: host
          - name: RABBITMQ_USERNAME
            valueFrom:
              configMapKeyRef:
                name: rabbitmq
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: rabbitmq
                key: password
          - name: S3_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: itunes-appstore-project
                key: s3.access-key-id
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: itunes-appstore-project
                key: s3.secret-access-key
          - name: S3_BUCKET
            valueFrom:
              configMapKeyRef:
                name: itunes-appstore-project
                key: s3.bucket
          - name: S3_BASE_PATH
            valueFrom:
              configMapKeyRef:
                name: itunes-appstore-project
                key: s3.base-path
          - name: AWS_KMS_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: itunes-appstore-project
                key: aws-kms.access-key

          - name: AWS_KMS_SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: itunes-appstore-project
                key: aws-kms.secret-key
          - name: AWS_KMS_ITUNESCONNECT_CREDENTIAL_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: itunes-appstore-project
                key: aws-kms.itunesconnect-credential-key-id
          - name: SENDGRID_APIKEY 
            valueFrom:
              configMapKeyRef:
                name: sendgrid
                key: apikey 
