apiVersion: v1
kind: Service
metadata:
  name: api-doc
  labels:
    name: api-doc
    http/proxy: enable
  annotations:
    http/host: api-doc.1sky.io
    http/max_resp_size: 20Mi
spec:
  selector:
    app: api-doc
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
