#!/bin/bash

# Usage: ./gen_config ENV TEMPLATE

export ENV=$1

if [ "$ENV" == "prod" ]; then
    echo "=== ENV=${ENV} ===" >&2
    export ENDPOINT_CWP=HAHA # let's get it done before production
    export ENDPOINT_CWP_API=api-cwp.1sky.io
    export ENDPOINT_INTERNAL_PORTAL=api-internal.1sky.io
    export ENDPOINT_TBACK_API=tback.1sky.io
    export ENDPOINT_IMPORT_ACTIVEMQ_ADMIN=import-activemq-admin.1sky.io
    export ENDPOINT_API_GW=apigw.1sky.io
    export ENDPOINT_WEBHOOK=webhook.1sky.io
elif [ "$ENV" == "kube-system" ]; then
    echo "=== ENV=${ENV} ===" >&2

elif [ "$ENV" == "stag" ]; then
    echo "=== ENV=${ENV} ===" >&2
    export REPLICAS=1 # dev should use 1 only, right?
    export ENDPOINT_CWP=stag-cwp.1sky.io
    export ENDPOINT_CWP_API=stag-api-cwp.1sky.io
    export ENDPOINT_CWP_API_EXPRESS=stag-api-cwp-express.1sky.io
    export ENDPOINT_INTERNAL_PORTAL=stag-api-internal.1sky.io
    export ENDPOINT_TBACK_API=stag-tback.1sky.io
    export ENDPOINT_API_GW=stag-apigw.1sky.io
    export ENDPOINT_WEBHOOK=stag-webhook.1sky.io
    export ENDPOINT_PROJECT_MANAGEMENT_API=stag-project-management-api.1sky.io
elif [ "$ENV" == "dev" ]; then
    echo "=== ENV=${ENV} ===" >&2
    export REPLICAS=1 # dev should use 1 only, right?
    export ENDPOINT_CWP=dev-cwp.1sky.io
    export ENDPOINT_CWP_API=dev-api-cwp.1sky.io
    export ENDPOINT_CWP_API_EXPRESS=dev-api-cwp-express.1sky.io
    export ENDPOINT_INTERNAL_PORTAL=dev-api-internal.1sky.io
    export ENDPOINT_TBACK_API=dev-tback.1sky.io
    export ENDPOINT_API_GW=dev-apigw.1sky.io
    export ENDPOINT_WEBHOOK=dev-webhook.1sky.io
    export ENDPOINT_SMS=dev-sms.1sky.io
    export ENDPOINT_SMS_API=dev-sms-api.1sky.io
    export ENDPOINT_PROJECT_MANAGEMENT_API=dev-project-management-api.1sky.io
    export ENDPOINT_MOCK_STRING_VIEWER=dev-mock-string-viewer.1sky.io
elif [ "$ENV" == "default" ]; then
    echo "=== ENV=${ENV} ===" >&2
    export ENDPOINT_USER_JOURNEY=user-journey.1sky.io


elif [ "$ENV" == "vendor" ]; then
    echo "=== ENV=${ENV} ===" >&2
    export REPLICAS=1 # dev should use 1 only, right?
    export LOGIN=vendor # defaul login name...

elif [ "$ENV" == "oursky" ]; then
    echo "=== ENV=${ENV} ===" >&2
    export REPLICAS=1 # dev should use 1 only, right?
    export LOGIN=oursky # defaul login name...

else
    echo '$ENV must be prod|stag|dev|default|kube-system, (vendor, oursky)!'
    echo ' or vendor namespaces: vendor | oursky'
    exit 1
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

$DIR/tools/templater.sh $2
