apiVersion: v1
kind: ReplicationController
metadata:
  name: ingress-controller
  namespace: kube-system
  labels:
    k8s-app: ingress-controller
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: ingress-controller
    version: v1
  template:
    metadata:
      labels:
        k8s-app: ingress-controller
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - name: romulus
          image: quay.io/timeline_labs/romulusd:c3608443
          args:
          - --kube-api=https://kubernetes.default
          - --kube-insecure
          - --provider=vulcand
          - --vulcand-api=http://vulcan-api.default.svc.cluster.local:8182
          - --selector=route=public
