apiVersion: v1
data:
  jwt.secret: YWJjZDEyMzQ=
  api.version: djE=
  logentries.token: YWNjY2RhNjMtYmJmYS00MDJmLTg1MzctODJlYTJiODhhOWY0
  raygun.token: ZTlRaXVUaE5MZktjU3d3eUN1KzBZUT09
  stripe.publishable.key: cGtfdGVzdF95Y01oNHg2ell2YVp6bTBxOE1INTdVTkE=
  zendesk: b25lc2t5aGVscDIuemVuZGVzay5jb20=
  intercom.app.id: ZHlndTRuajI=
  ga: VUEtMzA1MjY0MzktNw==
  heap: Nzk5Nzg0MzEx
  cdn: c3RhdGljLm9uZXNreWNkbi5jb20vY2xpZW50LXdlYi1wb3J0YWw=
kind: Secret
metadata:
  name: client-web-portal
  namespace: stag
type: Opaque
