apiVersion: v1
kind: Service
metadata:
  name: api-gateway-tyk-redis
  labels:
    name: api-gateway-tyk-redis
spec:
  selector:
    app: api-gateway-tyk-redis
  ports:
  - name: redis
    port: 6379
    targetPort: redis
    protocol: TCP

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: api-gateway-tyk-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway-tyk-redis
    spec:
      containers:
      - name: api-gateway-tyk-redis
        image: redis:3.0.7
        ports:
        - containerPort: 6379
          name: redis
        resources:
          limits:
            cpu: 200m
            memory: 256Mi