apiVersion: v1
kind: Service
metadata:
  name: client-web-portal-api
  labels:
    name: client-web-portal-api
    http/proxy: enable
  annotations:
    http/host: api-cwp.1sky.io
    http/max_resp_size: 20Mi
spec:
  selector:
    app: api-gateway-tyk
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: internal-portal-api
  labels:
    name: internal-portal-api
    http/proxy: enable
  annotations:
    http/host: api-internal.1sky.io
    http/max_resp_size: 20Mi
spec:
  selector:
    app: api-gateway-tyk
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: api-gateway-tyk
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: api-gateway-tyk
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: api-gateway-tyk
        image: quay.io/onesky/api-gateway-tyk:0.1.0
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
        env:
          - name: REDIS_HOST
            value: "api-gateway-tyk-redis.default.svc.cluster.local"
