apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: api-gateway
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: api-gateway
        image: quay.io/onesky/api-gateway:0.1.0
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
          - name: LOG_LEVEL
            value: "INFO"
          - name: ITUNES_APPSTORE_PROJECT_SERVICE_ADDRESS
            value: "itunes-appstore-project.default.svc.cluster.local"
          - name: RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: host
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: password
