apiVersion: v1
kind: Service
metadata:
  name: api-gateway-tyk
  labels:
    name: api-gateway-tyk
    http/proxy: enable
  annotations:
    http/host: api-cwp.1sky.io
    http/max_resp_size: 20Mi
spec:
  selector:
    app: api-gateway-tyk
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: api-gateway-tyk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway-tyk
    spec:
      containers:
      - name: api-gateway-tyk
        image: quay.io/onesky/api-gateway-tyk:0.0.1
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 256Mi

      - name: tyk-temp-redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
