apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    name: api-gateway
    http/proxy: disabled # API Gateway is private, only TYK is public
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: api-gateway
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: api-gateway
        image: quay.io/onesky/api-gateway:0.0.1
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
