apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: docker2le
  name: docker2le
spec:
  template:
    metadata:
      labels:
        app: docker2le
      name: docker2le
    spec:
      containers:
      - env:
        - name: DOCKER_LE_CONFIG 
          valueFrom:
            configMapKeyRef:
              name: docker2le
              key: config
        image: quay.io/onesky/docker2le:0.1.5
        name: docker2le
        resources:
          requests:
            cpu: 100m
            memory: 32Mi
          limits:
            cpu: 500m
            memory: 64Mi
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: dockerapi
      imagePullSecrets:
      - name: quay
      volumes:
      - name: dockerapi
        hostPath:
          path: /var/run/docker.sock

