apiVersion: v1
kind: Service
metadata:
  name: import-activemq
  labels:
    name: import-activemq
spec:
  selector:
    component: import-activemq-master
  ports:
  - name: broker
    port: 61616
    targetPort: broker
    protocol: TCP

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: import-activemq-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: import-activemq-master
    spec:
      containers:
      - name: import-activemq-master
        image: quay.io/onesky/activemq:5.13.2
        ports:
        - containerPort: 61616
          name: broker
        - containerPort: 8161
          name: admin

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: import-activemq-slave
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: import-activemq-slave
    spec:
      containers:
      - name: import-activemq-slave
        image: quay.io/onesky/activemq:5.13.2
        ports:
        - containerPort: 61616
          name: broker