apiVersion: v1
kind: Service
metadata:
  name: client-web-portal
  namespace: {{ENV}}
  labels:
    app: client-web-portal
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
  selector:
    app: client-web-portal

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: client-web-portal 
  namespace: {{ENV}}
spec:
  rules:
    - host: {{ENDPOINT_CWP}} 
      http:
        paths:
          - path: /
            backend:
              serviceName: client-web-portal
              servicePort: 8080

