apiVersion: v1
kind: Service
metadata:
  name: client-web-portal
  namespace: {{ENV}}
  labels:
    app: client-web-portal
    http/proxy: enable
  annotations:
    http/host: {{ENDPOINT_CWP}} # And here
    # http/auth: 1sky:passwordTBC # For internal, actual password will be overriden at live
spec:
  ports:
    # the port that this service should serve on
  - port: 8080
    targetPort: 8080
  selector:
    app: client-web-portal
