apiVersion: v1
kind: Service
metadata:
  namespace: {{ENV}}
  name: user-journey 
  labels:
    name: user-journey 
    http/proxy: enable
  annotations:
    http/host: {{ENDPOINT_USER_JOURNEY}}
    http/max_resp_size: 20Mi
spec:
  selector:
    app: user-journey
  ports:
  - name: http
    port: 80
    targetPort: http 
    protocol: TCP
