apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ENV}}
  name: client
spec:
  revisionHistoryLimit: 2
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: client
        image: quay.io/onesky/client:{{IMG_VERSION}}
        ports:
        - containerPort: 50051
          name: rpc
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
          - name: JAVA_TOOL_OPTIONS
            value: "-Xms128m -Xmx500m"
          - name: PGSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: client
                key: pgsql.host
          - name: PGSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: client
                key: pgsql.database
          - name: PGSQL_PORT
            valueFrom:
              configMapKeyRef:
                name: client
                key: pgsql.port
          - name: PGSQL_USERNAME
            valueFrom:
              configMapKeyRef:
                name: client
                key: pgsql.username
          - name: PGSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: client
                key: pgsql.password

          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: rabbitmq
                key: host
          - name: RABBITMQ_USERNAME
            valueFrom:
              configMapKeyRef:
                name: rabbitmq
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: rabbitmq
                key: password

          - name: TYK_HOST
            value: client-web-portal-api.{{ENV}}.svc.cluster.local
          - name: TYK_SECRET
            valueFrom:
              configMapKeyRef:
                name: tyk
                key: secret