apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  namespace: {{ENV}}
  name: iwp-api
spec:
  revisionHistoryLimit: 2
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: iwp-api
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: iwp-api
        image: quay.io/onesky/iwp-api:{{IMG_VERSION}}
        ports:
        - containerPort: 3000
          name: http 
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
          - name: AUTH0_CLIENT_SECRET
            valueFrom:
              configMapKeyRef:
                name: iwp-api
                key: auth0.client.secret
          - name: AUTH0_CLIENT_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: iwp-api
                key: auth0.client.domain
          - name: AUTH0_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: iwp-api
                key: auth0.client.id
          - name: AUTH0_REDIRECT_URI
            valueFrom:
              configMapKeyRef:
                name: iwp-api
                key: auth0.redirect.uri