apiVersion: v1
kind: Service
metadata:
  namespace: {{ENV}}
  name: appstore-integration 
spec:
  selector:
    app: appstore-integration 
  ports:
  - name: rpc
    port: 50051
    targetPort: rpc
    protocol: TCP
