apiVersion: v1
kind: ReplicationController
metadata:
  name: ordering
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ordering
    spec:
      containers:
      - name: ordering
        image: quay.io/onesky/ordering:0.0.1-alpha3
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: ordering
              key: postgres.host
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: ordering
              key: postgres.username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ordering
              key: postgres.password
        - name: POSTGRES_PORT
          value: "5432"
      imagePullSecrets:
      - name: quay
