apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  namespace: {{ENV}}
  name: api-gateway
spec:
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: api-gateway
        image: quay.io/onesky/api-gateway:{{IMG_VERSION}}
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
          - name: JAVA_TOOL_OPTIONS 
            value: "-Xms128m -Xmx500m"
          - name: LOG_LEVEL
            value: "INFO"
          - name: CLIENT_SERVICE_ADDRESS
            value: "client.{{ENV}}.svc.cluster.local"
          - name: ITUNES_APPSTORE_PROJECT_SERVICE_ADDRESS
            value: "itunes-appstore-project.{{ENV}}.svc.cluster.local"
          - name: ITUNES_CONNECT_SERVICE_ADDRESS
            value: "itunes-appstore-project.{{ENV}}.svc.cluster.local"
          - name: ORDERING_SERVICE_ADDRESS
            value: "ordering.{{ENV}}.svc.cluster.local"
          - name: COMMUNICATION_SERVICE_ADDRESS
            value: "communication.{{ENV}}.svc.cluster.local"
          - name: ITUNES_ORDER_SERVICE_ADDRESS 
            value: "itunes-appstore-project.{{ENV}}.svc.cluster.local"
          - name: REALTIME_COMMUNICATION_SERVICE_ADDRESS
            value: "realtime-communication.{{ENV}}.svc.cluster.local"
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: client-web-portal
                key: jwt.secret
