apiVersion: v1
kind: Service
metadata:
  namespace: {{ENV}}
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-gateway
  namespace: {{ENV}}
spec:
  rules:
    - host: {{ENDPOINT_API_GW}} 
      http:
        paths:
          - path: /
            backend:
              serviceName: api-gateway 
              servicePort: http 
    - host: {{ENDPOINT_WEBHOOK}} 
      http:
        paths:
          - path: /
            backend:
              serviceName: api-gateway 
              servicePort: http 
