apiVersion: v1
kind: Service
metadata:
  namespace: {{ENV}}
  name: api-gateway-tyk-redis
spec:
  selector:
    app: api-gateway-tyk-redis
  ports:
  - name: redis
    port: 6379
    targetPort: redis
    protocol: TCP
