apiVersion: v1
kind: Service
metadata:
  namespace: {{ENV}}
  name: api-gateway-tyk
  labels:
    name: api-gateway-tyk
spec:
  selector:
    app: api-gateway-tyk
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: client-web-portal-api 
  namespace: {{ENV}}
spec:
  rules:
    - host: {{ENDPOINT_CWP_API}} 
      http:
        paths:
          - path: /
            backend:
              serviceName: api-gateway-tyk
              servicePort: http 

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: internal-portal-api 
  namespace: {{ENV}}
spec:
  rules:
    - host: {{ENDPOINT_INTERNAL_PORTAL}} 
      http:
        paths:
          - path: /
            backend:
              serviceName: api-gateway-tyk
              servicePort: http 

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webhook 
  namespace: {{ENV}}
spec:
  rules:
    - host: {{ENDPOINT_WEBHOOK}} 
      http:
        paths:
          - path: /
            backend:
              serviceName: api-gateway-tyk
              servicePort: http 

