apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  namespace: {{ENV}}
  name: api-gateway-tyk
spec:
  revisionHistoryLimit: 2
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: api-gateway-tyk
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: api-gateway-tyk
        image: quay.io/onesky/api-gateway-tyk:{{IMG_VERSION}}
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
        env:
          - name: JAVA_TOOL_OPTIONS 
            value: "-Xms128m -Xmx240m"
          - name: SECRET
            valueFrom:
              configMapKeyRef:
                name: tyk
                key: secret
          - name: REDIS_HOST
            value: "api-gateway-tyk-redis.{{ENV}}.svc.cluster.local"
          - name: CLIENT_WEB_PORTAL_JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: client-web-portal
                key: jwt.secret
          - name: ENDPOINT_API_GATEWAY 
            value: "http://api-gateway.{{ENV}}.svc.cluster.local"
          - name: ENDPOINT_CWP_API
            value: "{{ENDPOINT_CWP_API}}" 
          - name: ENDPOINT_INTERNAL_PORTAL 
            value: "{{ENDPOINT_INTERNAL_PORTAL}}"
