apiVersion: v1
kind: Service
metadata:
  namespace: {{ENV}}
  name: client-web-portal-api
  labels:
    name: client-web-portal-api
spec:
  selector:
    app: api-gateway-tyk
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: client-web-portal-api 
  namespace: {{ENV}}
spec:
  rules:
    - host: {{ENDPOINT_CWP_API}} 
      http:
        paths:
          - path: /
            backend:
              serviceName: client-web-portal-api
              servicePort: http 

