apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  namespace: {{ENV}}
  name: cwp-api
spec:
  revisionHistoryLimit: 2
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: cwp-api
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: cwp-api
        image: quay.io/onesky/cwp-api:{{IMG_VERSION}}
        ports:
        - containerPort: 3000
          name: http 
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
          - name: PROJECT_SERVICE_ADDRESS
            value: "project-management.{{ENV}}.svc.cluster.local"
          - name: LANGUAGE_SERVICE_ADDRESS
            value: "language.{{ENV}}.svc.cluster.local"
          - name: CLIENT_SERVICE_ADDRESS
            value: "client-new.{{ENV}}.svc.cluster.local"
          - name: DIRECTORY_SERVICE_ADDRESS
            value: "directory.{{ENV}}.svc.cluster.local"
          - name: JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: cwp-api
                key: jwt.secret
          - name: AUTH0_JWT_SECRET
            valueFrom:
              configMapKeyRef:
                name: cwp-api
                key: auth0.jwt.secret
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: rabbitmq
                key: host
          - name: RABBITMQ_USERNAME
            valueFrom:
              configMapKeyRef:
                name: rabbitmq
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: rabbitmq
                key: password