apiVersion: v1
kind: Service
metadata:
  name: import-activemq
spec:
  selector:
    component: import-activemq-master
  ports:
  - name: broker
    port: 61616
    targetPort: broker
    protocol: TCP