apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  namespace: {{ENV}}
  name: language
spec:
  revisionHistoryLimit: 2
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: language
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: language
        image: quay.io/onesky/language:{{IMG_VERSION}}
        ports:
        - containerPort: 50051
          name: rpc
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
          - name: PGSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: language
                key: pgsql.host
          - name: PGSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: language
                key: pgsql.database
          - name: PGSQL_USERNAME
            valueFrom:
              configMapKeyRef:
                name: language
                key: pgsql.username
          - name: PGSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: language
                key: pgsql.password
          - name: PGSQL_PORT
            value: "5432"


