apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ENV}}
  name: directory
spec:
  revisionHistoryLimit: 2
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: directory
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: directory
        image: quay.io/onesky/directory:{{IMG_VERSION}}
        ports:
        - containerPort: 50051
          name: rpc
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
          - name: PGSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: client
                key: pgsql.host
          - name: PGSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: client
                key: pgsql.database
          - name: PGSQL_PORT
            valueFrom:
              configMapKeyRef:
                name: client
                key: pgsql.port
          - name: PGSQL_USERNAME
            valueFrom:
              configMapKeyRef:
                name: client
                key: pgsql.username
          - name: PGSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: client
                key: pgsql.password