apiVersion: v1
kind: ReplicationController
metadata:
  name: itunes-appstore-project
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: itunes-appstore-project
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: itunes-appstore-project
        image: quay.io/onesky/itunes-appstore-project:0.1.0-alpha7
        ports:
        - containerPort: 50051
          name: rpc
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: itunes-appstore-project
                key: postgres.host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: itunes-appstore-project
                key: postgres.port
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: itunes-appstore-project
                key: postgres.username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: itunes-appstore-project
                key: postgres.password
