apiVersion: v1
kind: ReplicationController
metadata:
  namespace: {{ENV}}
  name: itunes-appstore-project
spec:
  replicas: {{REPLICAS}} 
  template:
    metadata:
      labels:
        app: itunes-appstore-project
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: itunes-appstore-project
        image: quay.io/onesky/itunes-appstore-project:{{IMG_VERSION}}
        ports:
        - containerPort: 50051
          name: rpc
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
          - name: ORDERING_SERVICE_ADDRESS
            value: "ordering.{{ENV}}.svc.cluster.local"
          - name: ITUNES_TRANSLATION_ADDRESS
            value: "itunes-translation.{{ENV}}.svc.cluster.local"
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: itunes-appstore-project
                key: postgres.host
          - name: POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: itunes-appstore-project
                key: postgres.database
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: itunes-appstore-project
                key: postgres.port
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: itunes-appstore-project
                key: postgres.username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: itunes-appstore-project
                key: postgres.password
          - name: RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: host
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: password
