apiVersion: v1
kind: Service
metadata:
  namespace: {{ENV}}
  name: project-management
spec:
  selector:
    app: project-management
  ports:
  - name: rpc
    port: 50051
    targetPort: rpc
    protocol: TCP
