apiVersion: v1
kind: ReplicationController
metadata:
  name: api-gateway-tyk-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway-tyk-redis
    spec:
      containers:
      - name: api-gateway-tyk-redis
        image: redis:3.0.7
        ports:
        - containerPort: 6379
          name: redis
        resources:
          limits:
            cpu: 200m
            memory: 256Mi