apiVersion: v1
kind: ReplicationController
metadata:
  namespace: {{ENV}}
  name: api-gateway-tyk
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: api-gateway-tyk
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: api-gateway-tyk
        image: quay.io/onesky/api-gateway-tyk:0.6.0
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
        env:
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: tyk
                key: secret
          - name: REDIS_HOST
            value: "api-gateway-tyk-redis.{{ENV}}.svc.cluster.local"
          - name: CLIENT_WEB_PORTAL_JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: client-web-portal
                key: jwt.secret
