apiVersion: v1
kind: Service
metadata:
  namespace: {{ENV}}
  name: client-web-portal-api
  labels:
    name: client-web-portal-api
    http/proxy: enable
  annotations:
    http/host: {{ENDPOINT_CWP}}
    http/max_resp_size: 20Mi
spec:
  selector:
    app: api-gateway-tyk
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
