apiVersion: v1
kind: Service
metadata:
  namespace: {{ENV}}
  name: sms-api 
spec:
  selector:
    app: sms-api
  ports:
  - name: http 
    port: 8000
    targetPort: 6543
    protocol: TCP
apiVersion: v1

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: sms-api
  namespace: {{ENV}}
spec:
  rules:
    - host: {{ENDPOINT_SMS_API}} 
      http:
        paths:
          - path: /
            backend:
              serviceName: sms-api
              servicePort: http 
