apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  namespace: {{ENV}}
  name: sms
spec:
  revisionHistoryLimit: 2
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: sms
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: sms
        image: quay.io/onesky/sms:{{IMG_VERSION}}
        ports:
        - containerPort: 50051
          name: rpc
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
          - name: PGSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: sms
                key: pgsql.host
          - name: PGSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: sms
                key: pgsql.database
          - name: PGSQL_USERNAME
            valueFrom:
              configMapKeyRef:
                name: sms
                key: pgsql.username
          - name: PGSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: sms
                key: pgsql.password
          - name: PGSQL_PORT
            value: "5432"
          - name: NO_RABBITMQ 
            value: "true"
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: rabbitmq 
                key: host
          - name: RABBITMQ_PORT
            valueFrom:
              configMapKeyRef:
                name: rabbitmq 
                key: port
          - name: RABBITMQ_USERNAME
            valueFrom:
              configMapKeyRef:
                name: rabbitmq 
                key: username 
          - name: RABBITMQ_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: rabbitmq 
                key: password 
          - name: RABBITMQ_VHOST
            valueFrom:
              configMapKeyRef:
                name: rabbitmq 
                key: vhost 
          - name: LAYER_APP_ID
            valueFrom:
              configMapKeyRef:
                name: sms
                key: grpc.layer_app_id
          - name: LAYER_TOKEN
            valueFrom:
              configMapKeyRef:
                name: sms
                key: grpc.layer_token
          - name: CWP_ORDER_SERVICE_ADDRESS
            value: "127.0.0.1"




