apiVersion: v1
kind: ReplicationController
metadata:
  name: client
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: client
        image: quay.io/onesky/client:c0bf265c8c7fe5d6d2ba6af19f63d8579eced3d2-SNAPSHOT
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
