apiVersion: v1
kind: ReplicationController
metadata:
  namespace: {{ENV}}
  name: client
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: client
        image: quay.io/onesky/client:0.1.0
        ports:
        - containerPort: 50051
          name: rpc
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
          - name: POSTGRE_HOST
            valueFrom:
              secretKeyRef:
                name: client
                key: postgre.host
          - name: POSTGRE_PORT
            valueFrom:
              secretKeyRef:
                name: client
                key: postgre.port
          - name: POSTGRE_USERNAME
            valueFrom:
              secretKeyRef:
                name: client
                key: postgre.username
          - name: POSTGRE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: client
                key: postgre.password

          - name: RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: host
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: password

          - name: TYK_HOST
            value: client-web-portal-api.{{ENV}}.svc.cluster.local
          - name: TYK_SECRET
            valueFrom:
              secretKeyRef:
                name: tyk
                key: secret
