apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ENV}}
  name: communication
spec:
  revisionHistoryLimit: 2
  replicas: {{REPLICAS}}
  template:
    metadata:
      labels:
        app: communication
    spec:
      imagePullSecrets:
      - name: quay
      containers:
      - name: communication
        image: quay.io/onesky/communication:{{IMG_VERSION}}
        ports:
        - containerPort: 50051
          name: rpc
        resources:
          limits:
            cpu: 400m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 384Mi
        env:
          - name: JAVA_TOOL_OPTIONS 
            value: "-Xms128m -Xmx500m"
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: rabbitmq
                key: host
          - name: RABBITMQ_USERNAME
            valueFrom:
              configMapKeyRef:
                name: rabbitmq
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: rabbitmq
                key: password
          - name: ORDERING_SERVICE_ADDRESS
            value: "ordering.{{ENV}}.svc.cluster.local"
          - name: ITUNES_APPSTORE_ORDER_SERVICE_ADDRESS
            value: "itunes-appstore-project.{{ENV}}.svc.cluster.local"
          - name: PGSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: communication
                key: pgsql.host
          - name: PGSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: communication
                key: pgsql.database
          - name: PGSQL_PORT
            valueFrom:
              configMapKeyRef:
                name: communication
                key: pgsql.port
          - name: PGSQL_USERNAME
            valueFrom:
              configMapKeyRef:
                name: communication
                key: pgsql.username
          - name: PGSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: communication
                key: pgsql.password
          - name: LAYER_APP_ID
            valueFrom:
              configMapKeyRef:
                name: communication
                key: layer.app-id
          - name: LAYER_TOKEN
            valueFrom:
              configMapKeyRef:
                name: communication
                key: layer.token
          - name: LAYER_PROVIDER_ID
            valueFrom:
              configMapKeyRef:
                name: communication
                key: layer.provider-id
          - name: LAYER_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: communication
                key: layer.key-id
          - name: RSA_KEY_PATH
            valueFrom:
              configMapKeyRef:
                name: communication
                key: layer.rsa-key-path
